# Generated by Django 4.2.7 on 2024-02-14 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_station_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='image',
        ),
    ]
