# Generated by Django 4.2.7 on 2024-02-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_station_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='image',
        ),
    ]
